import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";
import '../globals.css'

export const metadata: Metadata = {
	title: "Auth",
	description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ClerkProvider
				appearance={{
					baseTheme: dark,
				}}>
				<body className={inter.className}>
					<main className="flex flex-row">
						<section className="main-container">
							<div className="w-full max-w-4xl">{children}</div>
						</section>
					</main>
				</body>
			</ClerkProvider>
		</html>
	);
}
