import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
	title: "Auth",
	description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ClerkProvider
				appearance={{
					baseTheme: dark,
				}}>
				<body className={inter.className}>{children}</body>
			</ClerkProvider>
		</html>
	);
}
